namespace: app
service:
  name: basic-login
  port: 8080
  image:
    path: bharathpantala/basic-login
    tag: latest

ingress:
  enabled: false
  host: dev01.cloudrural.net
  path: "/basic-login"

#environments:

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10
