namespace: app
service:
  name: basic-auth
  port: 8080
  image:
    path: basic-auth
    tag: 1.0.0-SNAPSHOT

ingress:
  host: app.cloudrural.net
  path: "/"

#environments:

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10
